### ISSUE TITLE
Energy.json Question

### ISSUE THREAD

**Issue by ChrisMurf2900** [nebulous/infinitude#151]
How does the energy.json get populated?
I'm not seeing any data in there, just "{}" unfortunately. I'm asking because it could be related to the 4.18 update I referenced in the MQTT issue line.
Just curious if there is a wait period or something. It would be awesome to get the kind of information that the Carrier/Bryant app gets for energy (Theirs only shows past days and not current. Not sure current is possible though?).

Thanks!

**Comment by nebulous** [comment]
Ah, yep I think that happens once/day. Glad to see it worked. To answer your question as to how it gets populated, whenever the thermostat makes an api request to Carrier's servers, Infinitude saves a copy of the request and response in the original xml format and in a transformed json format to make the content available. You can see all requests and their replies as files in your state folder, or access them via Infinitude. Some interesting examples are `/notifications.json` `/equipment_events.json` `/odu_status.json` `/idu_status.json` etc depending on your stat hardware/firmware version and equipment.

**Comment by mamarley** [comment]
I actually don't have a working infinitude instance right now because of the whole FW upgrade and MQTT stuff. :(  The energy usage also isn't of particular interest to me, given the low resolution of the data and the fact that my parents have a time-of-use rate plan and a solar energy system that invalidate the pricing data anyway.  I do still hope to get one of these at my house someday and I don't have TOU, so…
