### ISSUE TITLE
Websocket opened, but no streaming source found

### ISSUE THREAD

**Issue by MrMxyzptlk** [nebulous/infinitude#159]
I'm running the latest image in Docker, I can pull the webpage up for Infinitude but there is no data from my thermostat?

I have the host / port setup on the thermostat pointed to the external facing IP of Infinitude; I wasn't sure if it should just be the IP / port or http://IP / port? I currently have the HTTP in the string.

I have YSTXCCWIC01-B Infinity thermostat with the latest firmware.

Not sure where else to check?

This is in the logs: Websocket opened, but no streaming source found

**Comment by nebulous** [comment]
> This is in the logs: Websocket opened, but no streaming source found

The above message is just a warning, so unless you are using an RS485 serial adaptor with infinitude it can be ignored. That said, the log messages were definitely excessive, and they've been cranked down since this ticket was opened, so you might want to pull the latest image and try again.

> I have the host / port setup on the thermostat pointed to the external facing IP of Infinitude; I wasn't sure if it should just be the IP / port or http://ip/ / port? I currently have the HTTP in the string.

Just to clarify, the only settings that should be changed in your thermostat for Infinitude are the PROXY settings. Not the cloud server settings. On my thermostat they're found in Wireless->Advanced Settings->Manage proxy servers. Screenshots of mine if it helps(Infinitude is running on 192.168.1.4, port 3000):

![image](https://user-images.githubusercontent.com/177510/208151624-04d0db03-37e2-4c42-a9d2-a2d6329b690f.png)

![image](https://user-images.githubusercontent.com/177510/208151933-7e4c96bb-4869-46d3-ba00-351a1663c779.png)

**Comment by cvanover7** [comment]
I'm having this same issue, with a new install, I tried to open another issue under this release. Infinitude proxy seems to work fine, updated proxy settings like the screenshots above, but no data is going to the proxy. Wall control version 4.31, which I believe was recently released.

**Comment by MrMxyzptlk** [comment]
Thanks for the pics and update. I had already tried the IP only and 03000 as the port; no go.

I'm going to try from scratch again.

**Comment by jftaylorMn** [comment]
Based on comments for another issue (https://github.com/nebulous/infinitude/issues/160),  it looks like there is a problem with 4.31.  reverting to 4.05 might be the best option to try.

**Comment by cvanover7** [comment]
> Based on comments for another issue (#160), it looks like there is a problem with 4.31. reverting to 4.05 might be the best option to try.

How do we get the old version of the software to revert to?

**Comment by jftaylorMn** [comment]
Take a look at the comments related to issue (https://github.com/nebulous/infinitude/issues/148). Sources for prior firmware revisions are listed.  

There is a youtube video (https://www.youtube.com/watch?v=B9TmLCbFCto) from carrier that shows the actual process to do the "upgrade" from a USB drive.

**Comment by cvanover7** [comment]
> Take a look at the comments related to issue (#148). Sources for prior firmware revisions are listed.
> 
> There is a youtube video (https://www.youtube.com/watch?v=B9TmLCbFCto) from carrier that shows the actual process to do the "upgrade" from a USB drive.

I downgraded from 4.32 to 4.05 and the proxy is now receiving data from the wall controller.

**Comment by MrMxyzptlk** [comment]
So I downgraded to 'fix' this issue.
