### ISSUE TITLE
Hold API confusing and unreliable.

### ISSUE THREAD

**Issue by electricessence** [nebulous/infinitude#180]
Of course let me start by saying THANK YOU for what you've done here.  It truly has made a huge impact in my quality of life.

I just have one nuanced issue that I'm struggling with.
When setting the hold mode, especially when providing a "until time" (otmr), it very commonly fails.  `{status:"fail"}`.
I feel like there might be reason, but I can't seem to figure it out.
I notice that I can poke at the API repeatedly in various ways to get it to not fail.  Typically my last ditch attempt is to set the hold to "off" and then set it back again to "on", but I worry that's not ideal for the system.

Any help here?

**Comment by electricessence** [comment]
Sorry, to be clear, I may have been calling the wrong end point.
I just looked at your infinitude perl script and it appears to have a specific endpoint for hold.
Investigating.

**Comment by nebulous** [comment]
Is this the endpoint you're calling? 

https://github.com/nebulous/infinitude/wiki/Infinitude-API-calls#set-hold

If you provide examples of what you're trying, what's happening, and what you expect instead, I'll see if I can reproduce.

**Comment by electricessence** [comment]
Yeah, I'm calling the config API.
I'm using the same pathways that the Home Assistant integration is using.

**Comment by electricessence** [comment]
One sec.  I'll get an example.

**Comment by electricessence** [comment]
`/api/config/zones/zone/${zoneId-1}` and I POST the variables to that (form encoded):
hold=on
currentActivity=manual
otmr=16:15 (or any 15 minute 24 hour value)

For the most part this end point works, but I've found that it is the least reliable when setting the otmr value.
But if I was just turning on and off hold with no otmr, it would work almost all the time.
But now, I'm trying to tweak my 'until' times.

**Comment by electricessence** [comment]
Looks like the hold API you've listed only returns XML?

**Comment by nebulous** [comment]
That looks reasonable, and is basically what the hold API does under the covers other than some minor conveniences like automatically rounding to the nearest 15m interval. And yes, it looks like [the commit which added](https://github.com/nebulous/infinitude/commit/44be260fa8688d55383494e346aaa8bae59c218e) that feature 9 years ago for some reason returned the XML representation of the config file as the thermostat accepts it rather than the slightly-less-terrible json translation. Seems worth changing the default there, although the return value isn't particularly useful in any case. I just tested it in a quick and dirty fashion by hitting `http://192.168.1.3:3000/api/1/hold.json?until=13:15` which seemed to work in my case. Are you using GET or POST? Does the hold endpoint ever fail? What's the load like on the machine running Infinitude?

**Comment by electricessence** [comment]
I'm using POST for anything that "modifies" a setting.
I haven't been using the `/api/[zoneId]/hold` endpoint, but I'm going to try it.

The load is minimal.  A docker container on a Synology that never gets thrashed.
I was also gonna ask, do you have any guidelines as to how aggressive the infinitude API can be called?
For example, here's what I will commonly do:

a) set the heatpoint,
b) immediately after (no delay, effectively in parallel) set the hold mode.

Should I be adding a delay, or waiting when sending commands?  What about setting hold, and then setting it again? Does the system need time to process?

**Comment by electricessence** [comment]
Side note, this is for a Hubitat hub driver set.

**Comment by nebulous** [comment]
> I'm using POST for anything that "modifies" a setting.

👍 the mutating GETs drive me crazy but many legacy home automation devices require it.

> I haven't been using the /api/[zoneId]/hold endpoint, but I'm going to try it.

Cool, thanks for testing - I'd be interested in seeing if there's a difference. 

> The load is minimal. A docker container on a Synology that never gets thrashed.
I was also gonna ask, do you have any guidelines as to how aggressive the infinitude API can be called?
For example, here's what I will commonly do:
a) set the heatpoint,
b) immediately after (no delay, effectively in parallel) set the hold mode.

I'd recommend against that for sure. Not because Infinitude can't handle it, but because Infinitude can and the thermostat can't. So a race condition could occur where Infinitude's state gets ahead of/out of sync with, then subsequently overwritten by, the thermostat's state.

> Should I be adding a delay, or waiting when sending commands? What about setting hold, and then setting it again? Does the system need time to process?

Yeah - it may make sense to incorporate some queueing/state buffering/rate limiting within Infinitude such that it can quickly accept, then slowly dole out commands to the thermostat - but complexity like that could create more problems than it solves.

Rule of thumb: you can change as much as you like in any single /config call, but wait for the thermostat to update before calling again.

**Comment by electricessence** [comment]
Ok so first attempt using the ../hold endpoint worked well.
I'll make adjustments and keep testing.
Thanks for the word of warning on the potential race condition.

**Comment by electricessence** [comment]
I'll say again.  What you've done here has REAL LIFE impact.  Thank you!

**Comment by electricessence** [comment]
Things seem to be working well now.  Thanks for the help.

**Comment by nebulous** [comment]
Interesting. From the description it seems possible that the thermostat stores its running state and reverts back to said state when the timer expires. I wonder if the thermostat UI allows this to happen as well or if it does the equivalent of what you suggest: setting hold to off before pushing a new timer state. The latter is certainly doable on the backend, but I'm not certain if it would be a bug or a feature.

**Comment by electricessence** [comment]
Yeah, it never screws up from the actual thermostat. 
That said, this is aligned with my previous observation when attempting to change the hold until without the simplified hold endpoint.

It's quite a pain to get around this, as it seems that you have to wait until the status has changed to off before trying to update the until value.

So I have to stop any updates, ping the hold value until it changes to off, then set the until value again.

**Comment by electricessence** [comment]
So that did work by the way:

1) look and see if the existing known state is hold=on.
2) if **off**, proceed as normal regardless of the hold update.
3) else if **on** and the known until does not match the one requested, continue on to 4:
4) slow down any updates to prevent the state from getting out of sync
5) post [hold:off]
6) ping the `/api/status/:zoneId/hold` value until it changes to off.
7) once off, proceed as normal and await updates on at a normal schedule after a delay.

**Comment by electricessence** [comment]
@nebulous, so I know you're busy, but I'm back again with a bit of confusion.
When I make changes from the Infinitude web-api, it seems to work as expected.
But calling into the hold API still seems confusing and unreliable.
Reply if you have time.  I'm so close to getting this driver working well, but yet just out of reach.

**Comment by nebulous** [comment]
when you say web-api are you referring to clickops on the infinitude web interface? like here?
![image](https://github.com/user-attachments/assets/c4cd7009-3416-44fa-91de-07b8b4efed0a)
the above makes changes to the system state structure (as represented by systems.xml/systems.json), then [POSTs it all at once to infinitude](https://github.com/nebulous/infinitude/blob/master/public/app/scripts/controllers/main.js#L184).

the api endpoint to do the same edits [infinitude state in-place](https://github.com/nebulous/infinitude/blame/master/infinitude#L215)

each set the change flag, which triggers the thermostat to re-request state from the cloud (ie infinitude, and possibly Carrier depending on one's settings). I believe you when you say there's a difference in behavior but I'm not immediately seeing the difference in terms of how the data is processed. Is there a replicable test case?

**Comment by electricessence** [comment]
Thanks again for taking some time to reply.
That does give me a bit more clarity.  It appears to be changing the config value when you modify those?  Or is it just calling the same pathway as the hold API?
As we covered previously, there is the dedicated zone hold endpoint... But...
Like previously, I'm encountering very weird hold behavior and TBH, I just wish it worked the way I expect: return to the schedule when hold is set to off, or the until time expires.

1) Setting setpoints, and setting manual activity with hold on **appears to work as expected**.
It involves two steps: setting the setpoints for the manual activity configuration, then calling the hold api to set the activity (hold on is the default) and the until time which can be any 15 minute increment of a 24 hour time (hh:mm).

2) Setting hold to off, tends to work just fine, but also tends to revert to a state where:
a) the activity is "home" and b) the hold is "on", and c) mostly likely has an until time.  Which I would expect it to return to the schedule which may be something other than "home" and subsequently have hold "off".

3) Quite commonly, if set to manual and there's an until time, once the until time is reached, there's no change except the until value is has reverted to forever.

This feels like a situation where if I'm not using the API, eventually, the system figures things out and can get back in schedule.
But when I do, I feel like it gets stuck in a weird state that I'm basically guessing how to trick it to get back to normal.
My previous strategy of setting the hold to off first before changing the until time is a bit challenging to get to work reliably.

Thoughts?

**Comment by nebulous** [comment]
Test cases:


| | |
| --- | --- |
|  Changed on the thermostat itself, hold until 5pm ![image](https://github.com/user-attachments/assets/354a1983-c0cf-4104-a2fd-0771b05c4f89) | and at 5pm ![image](https://github.com/user-attachments/assets/1cc44fd5-68f0-4262-a858-f0418889dd64) |
| Changed via /api/1/hold `until=17:30` 
![image](https://github.com/user-attachments/assets/919f7530-b947-4c4c-b473-c8ac0e274a89) | and after 17:30 ![image](https://github.com/user-attachments/assets/d359226b-4b43-446b-a91d-f25ab851e6bf) |

frustratingly, it seems to JustWork® for me. Though perhaps my tests are invalid since I'm just having it hold `home` for now

**Comment by electricessence** [comment]
Just checked this:
/api/version
```json
{"data":"1.7","status":"success"}
```

**Comment by electricessence** [comment]
Replicating your test.

**Comment by electricessence** [comment]
Step 1:
Set manual until 16:30
`/api/1/hold`
```
activity=manual&until=16:30
```

**Comment by electricessence** [comment]
# Step 2:
Check the state of the system at 16:30
GET /api/config/zones/zone/0/
![image](https://github.com/user-attachments/assets/ed97012d-43e9-4aa5-8b20-c353fa63f137)

**Comment by electricessence** [comment]
I should have documented the initial conditions.
But it should have been in "home".  Going to try again.

**Comment by electricessence** [comment]
# Retry

### Initial Conditions
![image](https://github.com/user-attachments/assets/a4d46da4-e60c-4a2f-84cb-1ab5309bff5e)

**Comment by electricessence** [comment]
### After 16:45
This time it worked as expected.
![image](https://github.com/user-attachments/assets/17569fe9-06a9-4671-9db1-df61df25242e)

**Comment by electricessence** [comment]
I just did another test, where I did a full round trip of setting manual, then releasing the hold (hold=off), then adding an until time, and it worked as expected.

## Summary
Everything behaved exactly as I would expect it except for the first time.

**Comment by electricessence** [comment]
Since I've recently updated the driver code, things have been better, but my logging has become detailed and I can see when things misbehave.  Or at least sometimes, I wake up in the morning, and observe that the setting is still stuck on manual.

**Comment by nebulous** [comment]
> Just checked this: /api/version
> 
> ```json
> {"data":"1.7","status":"success"}
> ```

in case of confusion this is just returning the version string from systems.xml and has nothing to do with infinitude's api version.

**Comment by electricessence** [comment]
Ah ok.  I was struggling to verify the version I have.

**Comment by electricessence** [comment]
Going to close for now.
It's still an issue that things behave unreliably, but okay for now.
