### ISSUE TITLE
Missing Status Information

### ISSUE THREAD

**Issue by GitBeagle** [nebulous/infinitude#22]
We have a brand new 3 ton Greenspeed heat pump and modulating gas furnace.  When I callup the index.html file I do not see the same information as shown in the readme file.  The coil temperature, airflow and blower speed are missing.  The status and systems xml files do not contain this running status information either.

How can I get the heat pump and furnace running status information?

John

**Comment by nebulous** [comment]
The elements above come from the rs485 serial bus that the units all use to talk to one another. If you have an rs485 serial adaptor, Infinitude will optionally display data it interprets from that stream. Note however that this will likely require some adjustment since not every device outputs the same information in the same locations within the stream.
