### ISSUE TITLE
Where are some key values?

### ISSUE THREAD

**Issue by ehwest** [nebulous/infinitude#37]
Can you make a list of known values?  Like in what table / row is the outdoor temperature found?

Are there known set points?

**Comment by nebulous** [comment]
Are you referring to key/values in the serial stream or in the webservice?

Serial) we would very much like to make a comprehensive list, but community efforts to standardize a format fizzled a bit. Myself, @3tones, and @acd would all welcome contributions in this regard I'm sure. Many data elements are duplicated in multiple devices and tables, and they don't appear to be consistent between devices so the discovery process needs to be honed. There is some limited data in the wiki and ongoing discussion is taking place on the [cocoontech forums](http://cocoontech.com/forums/topic/11372-carrier-infinity/).

http) This is a simpler nut to crack since the data is already arranged in k/v form, but I'm not sure how it could get more specific.

**Comment by ehwest** [comment]
OK, but someone built a GUI with pretty dials and outputs, are those key/values a good starting point?

**Comment by ehwest** [comment]
[carrier_code_table.docx](https://github.com/nebulous/infinitude/files/823267/carrier_code_table.docx)
