### ISSUE TITLE
Debugging new serial setup

### ISSUE THREAD

**Issue by cheitzig** [nebulous/infinitude#46]
Hi,

I'm new to infinitude, but not new to Unix/linux, shell scripts, etc. I'm not deeply familiar with Perl, and am having trouble getting data to show-up in my infinitude site.

Here's what I have and what I've done:
- Raspberry Pi 3 running just fine, connected to network, etc.
- rs485 USB adapter installed and loading at /dev/ttyUSB0
- A/B wires connected using Cat 6 cable from ports A/B to RS485 adapter
- Infinitude installed and runs properly (e.g., base website seems to render)
- Compiled cardump and seem to be getting frames (see attached)

Would appreciate any thoughts on being able to see / display status?

[frames.txt](https://github.com/nebulous/infinitude/files/1693381/frames.txt)
![infinitudescreenshot](https://user-images.githubusercontent.com/733932/35783107-d8b9e36a-09c7-11e8-8b1f-4eed3ad96cf5.png)

**Comment by cheitzig** [comment]
A little bit more info: I got infinitive running just fine, so maybe it's something with the infinitude configuration on Bryant?

**Comment by nebulous** [comment]
Hi. It looks like cardump proves your physical serial interface is working properly. Since you say you got Infinitive working, does that mean you have a non-touch thermostat? Infinitude is designed to replace the public webservice for internet-connected touch thermostats, while Infinitive is designed to connect non-internet-connected thermostats to the internet. However, the serial monitor in Infinitude should work to view serial traffic regardless, if things are properly configured. The main thing that I notice about the screenshot above is that you don't appear to have all of the css/js loading (which would definitely cause failure to connect to Infinitude's websocket).

Here is what yours should roughly look like when operating in production mode:
![image](https://user-images.githubusercontent.com/177510/35808527-0b4cfc7c-0a54-11e8-93bb-a048a883a153.png)


I have a few features not-yet-in-the-repository visible in that screenshot, but you should see the tabs/colors/etc if everything is working.

How are you starting up Infinitude? Are there any errors visible?

**Comment by cheitzig** [comment]
I re-installed infinitude tonight, although I'm not sure if that was required. I also realized that I was probably running it incorrectly, so I fixed that too. Now, it's at least showing information on the status screen. I was actually seeing the CSS version of the webpage before; I think that potentially what fixed things was running cardump, which, based on another post I saw, resets the serial adapter.

What I'm seeing on the home screen is very similar to what issue #45 is showing, which, based on your response to that issue, is roughly what I should be seeing.

So I think I can close this issue. Infinitive does what I need it to do, although I found infinitude first, so thanks for creating this software!
