### ISSUE TITLE
Not cached or passthru disabled?

### ISSUE THREAD

**Issue by swerb73** [nebulous/infinitude#81]
If there is a better place to post this please let me know and apologies.  I have Infinitude installed on Windows 10 w/ Strawberry Perl and I've integrated the serial interface using the newer serial socket connection to the COM port.  At any rate the display all seems to work great, web interface and I think I've figured out the API calls.  Took me a while to realize it was only passing through the requests by default every 17m, but after changing it to many different options (15s, 60s, 120s, 180s) then back to the default 1020 (17m) I can't seem to ever get it to post to carrier/bryant back end and adjust the actual settings.  The API call comes back true with a good JSON response but even the infinitude web interface won't update.

What could I be missing?  I rand this in development mode and didn't find anything interesting other than periodically seeing a message like system XYZ not cached or passthru disabled?

Happy to post any logs or make the Infinitude interface available on the 'net to test with.

Thanks for any help.

**Comment by swerb73** [comment]
OK, a bit embarassed, was reading the docs wrong:
https://github.com/nebulous/infinitude/wiki/Infinitude-API-calls
I didn't realize the "scheduled" note at the bottom and thought this was supposed to change the activity mode in realtime and/or the set point...

If I'm reading this right the only way to change a setpoint then is to change the activity mode (home/away/etc) and put the zone on hold until a specific time?  For example:
/api/2/hold?activity=away&until=23:45

Puts zone 2 on hold until 11:45 and in away activity/mode?

There is no way for me to just change the htsp to say 70 degrees, I suppose it would be:
/api/2/hold?activity=manual&until=23:45

Noting it defaults to the future hour if I don't set until.

Thanks for any clarification!

**Comment by nebulous** [comment]
Hi @swerb73 - just took a look at the issue backlog and saw this question... Are you still having trouble with this? Infinitude sits in between the thermostat and Carrier's web service. Actually, it makes Carrier's webservice optional. I don't use Carrier's webservice - so it's possible something doesn't work as expected. Ultimately, settings are all stored on the thermostat in a big configuration structure. If your thermostat is connecting to infinitude, then infinitude should be able to modify your thermostat's settings. If passthru is non-zero, then requests from the thermostat will hit infinitude and also be allowed to pass thru to Carrier's service if it has been at least `passthru` seconds since the last time that has been done for any given endpoint.
